name: Tar.gz Processor

on:
  workflow_dispatch:
    inputs:
      LINK:
        description: 'The file link'
        required: true

      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up dependencies
      run: sudo apt-get install wget tree tar gzip
    
    - name: Tree at first
      run: tree -afsh \${{ github.workspace }}
        
    - name: Wget
      run: wget -nv '${{ github.event.inputs.LINK }}'
      
    - name: Tree after wget
      run: tree -afsh \${{ github.workspace }}
      
    - name: Run
      run: tar -zxvf *.tar.gz
      
    - name: Tree after unzip
      run: tree -afsh \${{ github.workspace }}

    - name: Process
      run: |
        rm -rf 
    
    - name: Tree after process
      run: tree -afsh \${{ github.workspace }}
      
    - name: Upload Aritfact (universal)
      uses: actions/upload-artifact@v4
      with:
        name: Downloaded file zip
        path: ${{ github.workspace }}/Z3150S
